### ISSUE TITLE
storeVersion does not return anything

### ISSUE THREAD

**Issue by mwerder** [SudoPlz/sp-react-native-in-app-updates#106]
I don't know what am I doing wrong... I am on the internal track for google play on version 1.39.31.317.
When I enter the play store I can see that there is an Update to 1.39.32
But the lib returns hasUpdate: false.
Furthermore storeVersion does not return anything, which should return "The latest app/play store version we're aware of"

"sp-react-native-in-app-updates": "^1.1.7",

```
inAppUpdates.checkNeedsUpdate().then(result => {
      console.log(result?.hasUpdate); // false
      console.log(result?.storeVersion); // undefined/empty
      console.log(result?.other); // totalBytes: 0, versionCode: 0, updateAvailability: 1, updatePriority: 0 ....
      if (result.shouldUpdate) {
        const updateOptions = Platform.select({
          ios: {
            title: 'Update available',
            message: 'There is a new version of the app available on the App Store, do you want to update it?',
            buttonUpgradeText: 'Update',
            buttonCancelText: 'Cancel',
          },
          android: {
            updateType: IAUUpdateKind.FLEXIBLE,
          },
        });
        inAppUpdates.startUpdate(updateOptions);
      }
    });
```

**Comment by mwerder** [comment]
ok seemed to be an issue with the internal track.
I used the internal app sharing with link and it seems to work now. Sorry for that!

**Comment by SudoPlz** [comment]
that was what I expected, no problem
