### ISSUE TITLE
App fails to install in debug mode on android with status code 5

### ISSUE THREAD

**Issue by Rajesh3R** [SudoPlz/sp-react-native-in-app-updates#11]
**I have face issue for install app** 

after UPDATE_DOWNLOADED status , I can not install app using  inAppUpdates.installUpdate() funcation,
after UPDATE_DOWNLOADED status, visible 3-5 second installation  screen then after installation screen invisible & 
inAppUpdates.addStatusUpdateListener(listner);  return status code 5, 
i check in mi device i currently checking in debug mode ,
please give me you positive response

**Comment by SudoPlz** [comment]
Not entirely sure what the issue is here, can you become more specific?
Maybe add an example with code?

Thanks

**Comment by Rajesh3R** [comment]
// Sorry for my bad english 
// I fallow below step
Step 1:  Click Update App button  update app 100 %
Step 2: show Install now  button visibale
Step 3: Click Install now button (call inAppUpdates.installUpdate();) 
step 4: now  listener  return status code 5 (Failed) 

// Here is my Example code  
import React, { Component } from "react";
import { Text, TouchableOpacity, View,  StyleSheet} from "react-native";
import SpInAppUpdates from 'sp-react-native-in-app-updates';
const inAppUpdates = new SpInAppUpdates();
const HIGH_PRIORITY_UPDATE = 5;
var listner = "";
const styles = StyleSheet.create({
  fontStyle: {
    fontSize:20,padding:3
  },
  updateStyle:{
    backgroundColor:'green',padding:30,marginTop:10
  }
})

export default class App extends React.Component{
  state = {
          download: false,
          all_status:[{"key":0,value:"UNKNOWN"},{"key":1,value:"UNAVAILABLE"},
                      {"key":2,value:"AVAILABLE / UPDATE_DOWNLOADING "},{"key":3,value:"UPDATE_INSTALLING"},
                      {"key":4,value:"UPDATE_INSTALLED"},{"key":5,value:"FAILED"},
                      {"key":6,value:"UPDATE_CANCELED"},{"key":7,value:"7"},
                      {"key":8,value:"8"},{"key":9,value:"9"},
                      {"key":10,value:"10"},{"key":11,value:"UPDATE_DOWNLOADED"}],
          app_status:0,
          total_byte:0,
          download_byte:0
      }
  componentDidMount(){
     listner = (status: UpdateStatus) => {
      if(status.status == SpInAppUpdates.UPDATE_STATUS.UPDATE_DOWNLOADED ){
        this.setState({download:true})
      }else if (status.status == SpInAppUpdates.UPDATE_STATUS.UPDATE_INSTALLED){
        inAppUpdates.removeStatusUpdateListener(listner)
      }
      this.setState({download_byte:status.bytesDownloaded,total_byte:status.totalBytesToDownload,app_status:status.status})
    };
    inAppUpdates.addStatusUpdateListener(listner);
  }

checkVersion(){
  inAppUpdates.checkNeedsUpdate({
    curVersion: '9',
  }).then(result => {
    if (result.shouldUpdate) {
        const updateType = result.other.updatePriority >= HIGH_PRIORITY_UPDATE
            ? SpInAppUpdates.UPDATE_TYPE.IMMEDIATE
            : SpInAppUpdates.UPDATE_TYPE.FLEXIBLE;
        inAppUpdates.startUpdate({
          updateType,
          }).then((result)=>{
            console.log("then startUpdate", result);
          }).catch((result) => {
        console.log("catch error ", result);
      })
    }else{
      alert("Not need to Update ")
    }
  }).catch((result) => {
      console.log("Something is wrong", result);
  })
}

installUpdate(){
  inAppUpdates.installUpdate();
}
render() {
  return (
        <View style={{paddingTop:25}}>
          <Text style={styles.fontStyle}> Status : {this.state.all_status[this.state.app_status].value}</Text>
          <Text style={styles.fontStyle}> Progress : {this.state.download_byte+" "}/{" "+this.state.total_byte}</Text>

          <TouchableOpacity onPress={()=>this.checkVersion()} style={styles.updateStyle}>
          <Text style={[styles.fontStyle,{color:'white'}]}>Update App</Text>
          </TouchableOpacity>

          {this.state.download && <TouchableOpacity onPress={()=>this.installUpdate()}style={styles.updateStyle}>
            <Text style={[styles.fontStyle,{color:'white'}]}>Install now </Text>
          </TouchableOpacity>}

        </View>
    )
}
}

**Comment by SudoPlz** [comment]
So the issue is you're getting status code 5 (failed) https://developer.android.com/reference/com/google/android/play/core/install/model/InstallStatus.html#FAILED.
This library does it's job (wrapping the native functionality and making it accessible to react-native) but you'll have to debug to figure out why you can't install your update and why you get a Failed status code - probably some miss-configuration.

I wish I could help you more but the issue is not within the scope of this library

**Comment by TokarAndrii** [comment]
I have the same error - @Rajesh3R have you found fix for it?
