### ISSUE TITLE
iOS : Getting latest version after 24 hours: Test Flight

### ISSUE THREAD

**Issue by testdevappapptest** [SudoPlz/sp-react-native-in-app-updates#129]
Hi @SudoPlz , Thank you for this library.

We recently added this plugin to our app. After App Store deployment, the Test Flight build(Version 1.5.1) is not getting the latest AppStore version(Version 1.5.2). In debug mode, I am getting the latest version. It took around 24 hours for the Test Flight build to get the new version. 
Note: In Android, we receive the most recent version immediately after deployment. 
Is there any way to reduce the delay in iOS?

**Comment by SudoPlz** [comment]
Hey there,

this is absolutely out of our control
This library is just wrapping native api's and has nothing to do with those delays.

😊
