### ISSUE TITLE
latest version from playstore is not being detected

### ISSUE THREAD

**Issue by Murali-mahadeva-BS** [SudoPlz/sp-react-native-in-app-updates#13]
I used react-native-version-check to check the latest from playstore. It worked there but react-native-in-app-updates is not detecting the latest version. Its giving should update as false. if i directly call the update function it says:

 [Error: sp-react-native-in-app-updates startUpdate error: Error: Update unavailable, check checkNeedsUpdate.updateAvailability first]

How can i make it to work

**Comment by abdollahzadehghalejoghi** [comment]
All this module does is wrapping the in-app-update sdk of Google, if that returns the wrong version it's outside the scope of this library.
Suggestion Debug the steps more accurately using the [Internal app sharing](https://play.google.com/console/u/0/internal-app-sharing)


> I used react-native-version-check to check the latest from playstore. It worked there but react-native-in-app-updates is not detecting the latest version. Its giving should update as false. if i directly call the update function it says:
> 
> [Error: sp-react-native-in-app-updates startUpdate error: Error: Update unavailable, check checkNeedsUpdate.updateAvailability first]
> 
> How can i make it to work

**Comment by alz10** [comment]
@Murali-mahadeva-BS I have the same experience. I also use `react-native-version-check` and it detects my app `versionName` which is `3.0` and it works perfectly, i was able to tell my users that there's an update available in playstore.

On the other hand, this library always throw a reason `status 1 means there's no new version available` no matter how i change the `curVersion`

**Comment by irfan102** [comment]
> @Murali-mahadeva-BS I have the same experience. I also use `react-native-version-check` and it detects my app `versionName` which is `3.0` and it works perfectly, i was able to tell my users that there's an update available in playstore.
> 
> On the other hand, this library always throw a reason `status 1 means there's no new version available` no matter how i change the `curVersion`

Same issue

**Comment by kanikas24** [comment]
> > @Murali-mahadeva-BS I have the same experience. I also use `react-native-version-check` and it detects my app `versionName` which is `3.0` and it works perfectly, i was able to tell my users that there's an update available in playstore.
> > On the other hand, this library always throw a reason `status 1 means there's no new version available` no matter how i change the `curVersion`
> 
Yes, facing the same issue.

**Comment by SudoPlz** [comment]
I think this may be related to https://github.com/SudoPlz/sp-react-native-in-app-updates/pull/18 which I'll work on today.

**Comment by SudoPlz** [comment]
You're probably having typical play issues.
Are you all using internal app sharing?
If not that's why the latest version is not detected.
https://stackoverflow.com/a/59456561/1658268).%03

**Comment by priyak-sdei** [comment]
Facing Same Issue. 
Always Getting shouldUpdate: false

Uploaded the App on Play-store as well.

**Comment by SudoPlz** [comment]
Try updating the play-core version https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/25#issuecomment-847220449

That being said, there's probably an issue with how you set up in-app-updates. It's still a trial and error process to get this right.
All this library does is wrap the native functionality, we don't really add anything to it, so as long as you have it configured properly, it should work great on react-native too.
Not sure how else I can help.

**Comment by wahidshadab** [comment]
The same happened for me too. It was returning false for should update.
Resetting google play store's cache and data on my device worked for me. I hope it works for others as well.

**Comment by bhaskarj61** [comment]
I am facing the same issue but if if clear my data and cache of play store app then it work fine.
Currently I am checking on Internal sharing, Will it work fine for production ?
