### ISSUE TITLE
Question about the curVersion

### ISSUE THREAD

**Issue by alz10** [SudoPlz/sp-react-native-in-app-updates#15]
1. Sorry, i just want to confirm. Is this the version from `package.json` or the versionName from `build.gradle`?
2. I already have an app available live on google playstore, do i need to upload a new apk first with this library installed in order to get an update? 

My app's `versionName` in build.gralde is `3.0` and i just found out about this package which i think is very useful, i use to tell my users about an apk update using `CodePush` but that's just a message and this library's implementation is amazing. Thanks

![image](https://user-images.githubusercontent.com/38030623/105673876-a4e59180-5f21-11eb-94bf-f1ee41aa0e6a.png)

**Comment by SudoPlz** [comment]
1. This totally depends on your current approach. If package.json is the source of truth of android versions, and android version reads from package.json then yeah.
Keep in mind you're comparing the incoming android in-app-update patch version with whatever you pass to `curVersion` which typically is the current android version.

2. That's just one way of doing it. Another thing I tried was, I modified the local version of my project to be lower than the one in the store, and then it would always prompt to update to the store version, even if they were technically the same version.

**Comment by alz10** [comment]
> 2.  I modified the local version of my project to be lower than the one in the store, and then it would always prompt to update to the store version, even if they were technically the same version.

I tried chaging the `curVersion` to `0.0.0` and the version in `package.json` to `0.0.0` as well and the result reason is always `status 1 means there's no new version available`

**Comment by SudoPlz** [comment]
Do you have code in your gradle file that reads the Android version from package.json? If not whatever version you're using in package.json is irrelevant, it's not read anywhere. Also, what version does the incoming update patch have? is there an incoming patch at all?

You have to take this step by step. Most people struggle because they don't know how to configure in app updates on Android. Remember this library is just a wrapper that exposes the functionality.

**Comment by ShivamJoker** [comment]
@SudoPlz can't this library get version from the gradle and compare automatically rather than manually providing it ?

I used this library for android, it didn't ask for current version - https://github.com/kumparan/react-native-android-inapp-updates

**Comment by SudoPlz** [comment]
Hi @ShivamJoker yeah that's an interesting suggestion. In our app we specifically wanted to avoid that, but I do see it may make sense for other projects.

That being said, it's very easy to get the app version using something like `react-native-device-info`.

**Comment by ShivamJoker** [comment]
@SudoPlz are you going to implement it or we will be needing to get it by using device info and provide it manually.

You can keep the function param optional and if user doesn't provide it then get it from native build itself ?

**Comment by SudoPlz** [comment]
Yeah that's what I was thinking too. I think I'll bake that in whenever I find some free time (no promises though).
A pr would be welcome if you'd like to give it a shot.

**Comment by ShivamJoker** [comment]
Sure I'll give it shot
