### ISSUE TITLE
force update in iOS

### ISSUE THREAD

**Issue by shahanshah-cutshort** [SudoPlz/sp-react-native-in-app-updates#150]
How to make user force update in iOS, like `IMMEDIATE` in android.

**Comment by RizqiSyahrendra** [comment]
Hi, it seems you've found the way, can you tell me how to do that?

**Comment by RizqiSyahrendra** [comment]
> Hi, it seems you've found the way, can you tell me how to do that?

I see, I can use `forceUpgrade` option, thank you
