### ISSUE TITLE
Example to add inappupdatePrriority

### ISSUE THREAD

**Issue by usuf16** [SudoPlz/sp-react-native-in-app-updates#16]
Can add some example where exactly we need to add the inappupdatepriority based on react native app. it will be more help full on completing the implementation.

**Comment by SudoPlz** [comment]
Hey @usuf16 , what do you mean?

There's an example in the readme, check the `result.other.updatePriority` section

**Comment by usuf16** [comment]
@SudoPlz that will result for setting the priority just my question is that where we need to set the priority in example "gradle.build"?

**Comment by SudoPlz** [comment]
You set the priority via the google play api, or whichever way you deliver the bundle to the play store. 
For example using fastlane, we specify: `in_app_update_priority`
https://docs.fastlane.tools/actions/upload_to_play_store/#uploading-an-apk
