### ISSUE TITLE
Added `<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" tools:node="remove"/>` in AndroidManifest.xml

### ISSUE THREAD

**Issue by abbasbphppoets** [SudoPlz/sp-react-native-in-app-updates#172]
i have use this but not work please give another solution 

 Added `<uses-permission android:name="com.google.android.finsky.permission.BIND_GET_INSTALL_REFERRER_SERVICE" tools:node="remove"/>` in AndroidManifest.xml

_Originally posted by @JeanSilvany in https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/146#issuecomment-1595485044_

**Comment by SudoPlz** [comment]
this is very vague, what is the issue? If it's the same as https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/146#issuecomment-1595485044 why are we opening a new ticket?
If it's a new issue feel free to reopen.
