### ISSUE TITLE
 RN Version 0.61.5 is Not working 

### ISSUE THREAD

**Issue by Mitdd9707** [SudoPlz/sp-react-native-in-app-updates#24]
![Screenshot_20210519_121933](https://user-images.githubusercontent.com/64424107/118768597-d3a2c180-b89c-11eb-8a7e-5f6a2983952c.jpg)

**I getting error above the image 
any one can help ?**

**Comment by SudoPlz** [comment]
Have you installed `react-native-device-info`?

Looks like it's missing.

**Comment by Mitdd9707** [comment]
@SudoPlz Yes I install properly still I faceing this issue

**Comment by SudoPlz** [comment]
I can't repro this, can you upload a simple reproduction project so that I can take a look?

Thank you
