### ISSUE TITLE
Critical issues reported with Play Core Library version

### ISSUE THREAD

**Issue by atryino** [SudoPlz/sp-react-native-in-app-updates#25]
The Play Core Library version being used is causing this message when uploading to the Play Store.

<img width="681" alt="Screen Shot 2021-05-24 at 8 17 30 AM" src="https://user-images.githubusercontent.com/6549653/119354133-547d0700-bc69-11eb-94a4-90d93c626241.png">

**Comment by SudoPlz** [comment]
You can overwrite the play core version yourself.
Check this line of code: https://github.com/SudoPlz/sp-react-native-in-app-updates/blob/master/android/build.gradle#L60

Go to your main `project/build.gradle` (NOT `project/app/build.gradle`), and add the following to your ext object:

ext {
    ...
    playCoreVersion = '1.9.1'
}

or whatever `playCoreVersion` you want to use.

**Comment by atryino** [comment]
Ah didn't catch that, thanks!
