### ISSUE TITLE
error google android play core

### ISSUE THREAD

**Issue by marciodiasdeveloper** [SudoPlz/sp-react-native-in-app-updates#28]
I am trying to act with library and getting the following error

'erro update', { [Error: sp-react-native-in-app-updates checkNeedsUpdate error: Error: com.google.android.play.core.internal.ar: Failed to bind to the service.]
  line: 248904,
  column: 22,
  sourceURL: 'http://10.0.2.2:8081/index.bundle?platform=android&dev=true&minify=false&app=br.com.toolzz.play&modulesOnly=false&runModule=true' }

**Comment by SudoPlz** [comment]
I think the issue is that you're not using a **REAL device**.

https://stackoverflow.com/a/60275447/1658268

**Comment by marciodiasdeveloper** [comment]
is my code correct? 
https://gist.github.com/marciodiasdeveloper/fce9e5ca1afc3d76b9bff22d89c1360e

**Comment by SudoPlz** [comment]
Hmm it looks right
