### ISSUE TITLE
setInstallSourceAndroid is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by ShivamJoker** [SudoPlz/sp-react-native-in-app-updates#30]
Are we going to get any fixes for this ?

**Comment by SudoPlz** [comment]
Are you sure you posted this to the right library?

That code is part of another github project that we're not using afaik:

https://github.com/dooboolab/react-native-iap/blob/master/src/iap.ts#L39-L48

**Comment by ShivamJoker** [comment]
Oh I'm really sorry. I thought this library was using that function 😅

**Comment by SudoPlz** [comment]
No worries mate.
