### ISSUE TITLE
Update com.google.android.play:core

### ISSUE THREAD

**Issue by mezalejandro** [SudoPlz/sp-react-native-in-app-updates#43]
On Play Store i have this message:
Your app contains a vulnerability that can lead to an attacker writing data to your app's internal storage. This is because your app is using an old version of the Play Core Library. Update the Play Core Library in your app to the latest version (1.7.2 or above).

Thanks

**Comment by SudoPlz** [comment]
https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/25#issuecomment-847220449
