### ISSUE TITLE
new NativeEventEmitter()` was called with a non-null argument

### ISSUE THREAD

**Issue by mdehghani65** [SudoPlz/sp-react-native-in-app-updates#48]
after upgrading to RN 0.66 I keep receiving these warnings when app starts:

 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.

I don't receive this warning if I comment out codes related to this package

**Comment by MicaelaWaigel** [comment]
The newest version of react native require that implement the addListener and removeListener methods.
The methods do not need to do anything, they just have to be there.

I resolved adding this to `SpReactNativeInAppUpdatesModules.java`
```
    @ReactMethod
    public void addListener(String eventName) {
        // Keep: Required for RN built in Event Emitter Calls.
    }

    @ReactMethod
    public void removeListeners(Integer count) {
        // Keep: Required for RN built in Event Emitter Calls.
    }
```

**Comment by mdehghani65** [comment]
> The newest version of react native require that implement the addListener and removeListener methods. The methods do not need to do anything, they just have to be there.
> 
> I resolved adding this to `SpReactNativeInAppUpdatesModules.java`
> 
> ```
>     @ReactMethod
>     public void addListener(String eventName) {
>         // Keep: Required for RN built in Event Emitter Calls.
>     }
> 
>     @ReactMethod
>     public void removeListeners(Integer count) {
>         // Keep: Required for RN built in Event Emitter Calls.
>     }
> ```

thx for replying

**Comment by SudoPlz** [comment]
Does anyone feel like adding those via a PR?
Thanks

**Comment by Hamuli-Team** [comment]
Thanks you! Its work!
