### ISSUE TITLE
Handling the cross icon press on the initial prompt for immediate update

### ISSUE THREAD

**Issue by radio-gra** [SudoPlz/sp-react-native-in-app-updates#50]
When `startUpdate` is called with `{updateType: IAUUpdateKind.IMMEDIATE}`, the promise gets resolved and a prompt is opened. If the user cancels the update in this stage by pressing the cross icon (circled in the screenshot), there seems to be no way to handle that because `startUpdate`'s promise has already been fulfilled by that point, and `addStatusUpdateListener`'s callback is not triggered until the user confirms the update. You're left in a kind of suspended position where you can only tell if the update is eventually accepted (via `addStatusUpdateListener`) but can't register if the cross button has ever been pressed.

I realize this might not be the problem with the library itself as i couldn't find any native solutions to this either, but maybe there's something i'm missing? For my use case (terminating if the user refuses or an error occurs) just quitting the app via `react-native-exit-app` after `startUpdate` seems to work, because when the update completes successfully you'd want to restart anyway, but this is very sloppy and i'd like to do this "properly".

![immediate_upd](https://user-images.githubusercontent.com/51534559/141081024-13b7d3c9-5370-4f71-a4bf-a9ba9ea2c52d.png)

**Comment by radio-gra** [comment]
I think i got it.

For anybody else who runs into this problem - there's an undocumented pair of functions `addIntentSelectionListener` & `removeIntentSelectionListener` that deal with the end result of the update in the same manner as `addStatusUpdateListener`/`removeStatusUpdateListener` deal with intermediate results. The callback will return `AndroidInstallStatus.CANCELED` code if you deny/cancel the update at any point or if anything else goes wrong.

```
const updatesModule = new SpInAppUpdates(true);
...
updatesModule.addIntentSelectionListener((intentResult) => {
    console.log(`intentResult: ${JSON.stringify(intentResult)}`); // = 6 on failure
});
```
It doesn't return anything on success, but that doesn't matter for immediate updates.

**Comment by danilvalov** [comment]
> For anybody else who runs into this problem - there's an undocumented pair of functions `addIntentSelectionListener` & `removeIntentSelectionListener` that deal with the end result of the update in the same manner as `addStatusUpdateListener`/`removeStatusUpdateListener` deal with intermediate results. The callback will return `AndroidInstallStatus.CANCELED` code if you deny/cancel the update at any point or if anything else goes wrong.
> 
> ```
> const updatesModule = new SpInAppUpdates(true);
> ...
> updatesModule.addIntentSelectionListener((intentResult) => {
>     console.log(`intentResult: ${JSON.stringify(intentResult)}`); // = 6 on failure
> });
> ```
> 
> It doesn't return anything on success, but that doesn't matter for immediate updates.

Thanks!

But there is a some interesting "feature" (undocumented too):
`InstallationResult` value in `intentResult` of `addIntentSelectionListener` has string type (`"6"` for cancelled), but `IAUInstallStatus.CANCELED` (aka `AndroidInstallStatus.CANCELED`) has number type (`6` for cancelled).

So correct example is:
```js
updatesModule.addIntentSelectionListener((intentResult) => {
    // fix for incorrect type of `intentResult`
    if (Number(intentResult) === IAUInstallStatus.CANCELED) {
      // your cancelled logic
    }
});
```
