### ISSUE TITLE
Due to use of com.google.android.play:core:1.7.1 ,  google play console showing Critical sdk issue in app

### ISSUE THREAD

**Issue by amityadav12239** [SudoPlz/sp-react-native-in-app-updates#54]
Warning from play console:
 
Your latest production release (42010506 (1.5.6)) contains SDK issues
Critical issues have been reported with the following SDK versions:

    com.google.android.play:core:1.7.1

What the SDK developer told us:
Your app contains a vulnerability that can lead to an attacker writing data to your app's internal storage. This is because your app is using an old version of the Play Core Library. Update the Play Core Library in your app to the latest version (1.7.2 or above).

**Comment by SudoPlz** [comment]
[Check this out](https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/25#issuecomment-847220449)

You should a new play core library version.
