### ISSUE TITLE
Android device app update popup is showing but in iOS devices I can't even see update popup

### ISSUE THREAD

**Issue by amit12239** [SudoPlz/sp-react-native-in-app-updates#55]

**Comment by SudoPlz** [comment]
What do you mean? What error are you getting?

**Comment by mardikarifqi** [comment]
This happened to my ios app. I think this is a react-native-siren's bug.

My app only released in a specific region. The siren library checks by calling `https://itunes.apple.com/lookup?bundleId=xxx`. In case of my app, I have to lookup using `https://itunes.apple.com/{countryCode}/lookup?bundleId=xxx`.

**Comment by SudoPlz** [comment]
Got it, yes you're probably right. Could you possibly open a bug report there, and link it to this issue? I'd be grateful.

Thanks

**Comment by ikhsanalatsary** [comment]
Hi @SudoPlz, I would like to help. I have already opened Pull Request. Please review it and let me know if you have any concerns or technical debt.

**Comment by SudoPlz** [comment]
Fix released with 1.1.5, thank you so much for putting that together @ikhsanalatsary .

**Comment by se09deluca** [comment]
👍🏻
