### ISSUE TITLE
Current behavior when user closes the app after triggering the IMMEDIATE UPDATE 

### ISSUE THREAD

**Issue by fareed945** [SudoPlz/sp-react-native-in-app-updates#56]
Hey,
Could you please provide info on the Current behavior when user closes the app after triggering the IMMEDIATE UPDATE .
Do we need to check for DEVELOPER_TRIGGERED_PROGRESS  and make the user install or is it handled already.

**Comment by SudoPlz** [comment]
This library just calls [startUpdateFlowForResult](https://developer.android.com/reference/com/google/android/play/core/appupdate/AppUpdateManager.html#startUpdateFlowForResult(com.google.android.play.core.appupdate.AppUpdateInfo,%20int,%20com.google.android.play.core.common.IntentSenderForResultStarter,%20int)) below the hood:  

https://github.com/SudoPlz/sp-react-native-in-app-updates/blob/3c55811c009db04a84203cfdf35bf63b78170bea/android/src/main/java/com/sudoplz/rninappupdates/SpReactNativeInAppUpdatesModule.java#L142

The docs suggest that you should indeed manually check for a `DEVELOPER_TRIGGERED_UPDATE_IN_PROGRESS` if the app is force closed. (The equivalent constant on this library is [UPDATE_DEV_TRIGGERED](https://github.com/SudoPlz/sp-react-native-in-app-updates/blob/3c55811c009db04a84203cfdf35bf63b78170bea/android/src/main/java/com/sudoplz/rninappupdates/SpReactNativeInAppUpdatesModule.java#L70).

Just check the `updateAvailability` value returned by `checkNeedsUpdate`
