### ISSUE TITLE
can't i use it with codepush??

### ISSUE THREAD

**Issue by moowoonsunghoon** [SudoPlz/sp-react-native-in-app-updates#57]
updating this package to a previous version using code push results in an error.

can't i use it with codepush??

**Comment by SudoPlz** [comment]
We're using code-push in production along with this package, but I don't know if you can "update" this package with code-push.
This is a code-push question, and totally unrelated to this library.

**Comment by moowoonsunghoon** [comment]
I'm sorry, I confused you because I'm not good at English.

What I'm trying to say is,
I installed this library and updated my app using code-push, but I got this error message.

```
{
 "line": 1050,
 "column": 1809,
 "sourceURL" : "..."
}
```

Do you know anything about this?

Thank you.

**Comment by SudoPlz** [comment]
Unfortunately not, I think that's indeed a codepush issue :/ I wish I could help more with your usecase
