### ISSUE TITLE
Please update com.google.android.play:core SDK to 1.7.2 or above (Critical Issue)

### ISSUE THREAD

**Issue by mardikarifqi** [SudoPlz/sp-react-native-in-app-updates#58]
![image](https://user-images.githubusercontent.com/16059055/148473552-4d480d92-0c76-4363-8411-777e7d7fab1e.png)

When releasing my app on the Play Store, I got a warning. Here's a [link](https://developer.android.com/reference/com/google/android/play/core/release-notes#1-7-2) to the bug. Play core latest version now is 1.10.+

**Comment by SudoPlz** [comment]
Either upgrade to the latest version of the library, or [manually pass another core version](https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/25#issuecomment-847220449)
.

**Comment by mardikarifqi** [comment]
Ah, I see. Thanks, hope this information got published in the README.md
