### ISSUE TITLE
My app gets closed when the update is installed.

### ISSUE THREAD

**Issue by wahidshadab** [SudoPlz/sp-react-native-in-app-updates#68]
I have followed the documentation and the example provided. My android app can detect the update and It can also download the app and install it. But, after installation my app is closed.  
What I want is to reload my app. I don't know if the library is working that way or there is a problem in my case? 
I have searched a lot about it. but, the only thing that I found was to define a new native module.

**Comment by SudoPlz** [comment]
It's not easy for me to help with the above information to be honest.

That being said, this library just wraps the google in-app-update API, it doesn't do anything other than invoke the native in-app-update functionality, so I think that's what you should be researching for, figuring out how the native InAppUpdate API works.

**Comment by wahidshadab** [comment]
I have already add an addStatusUpdateListener. I want it to be able to check if the installation is done or not.  If installation is completed I want to show a pop up to restart the app. but right now I don't get anything to detect the installation is done, instead my app is being closed. after the app is installed.
Here is how I have implemented it. 

`this.#inAppUpdates.addStatusUpdateListener(this.installUpdateListener);`


installUpdateListener = (event) => {

    const {status} = event;
    console.log('Installing update ...');
    if(status === 11){
      this.#inAppUpdates.installUpdate();
    }
    if(status === 4){
      console.log('installed update ...');
     // here I want to show the user a pop saying that the app will be reloaded if they accept it the app will reload using
      // RNRestart.Restart();
    }
  }

**Comment by wahidshadab** [comment]
I am trying to use IMMEDIATE in app update and I want the app to force users to download and install the update. When the gets mounted it will check for the update and if there is an available update, it will show a pop up menu saying it's recommended to update the app. when the user clicks on update, the app starts downloading update and after it's done downloading it install's the update and closes the app with out crashing the app or any sign of crash in logs. I am using internal app sharing for testing updates.

Expected behavior: 
What I want is, when it's done downloading and installing update. It should restart the app with installed update. 

The following is my code.

```
const HIGH_PRIORITY_UPDATE = 0; // Arbitrary, depends on how you handle priority in the Play Console

class App extends Component {

  #inAppUpdates;
  constructor(props) {
    super(props);
    this.#inAppUpdates = new SpInAppUpdates(
      false // isDebug
    );
  }
  
  checkForUpdate = () => {
    console.log('check for update called');
    this.#inAppUpdates
      .checkNeedsUpdate({})
      .then((updateResponse) => {
        console.log('update response is ...', updateResponse)
        if (updateResponse.shouldUpdate && updateResponse.other.updatePriority >= 0) {
          let updateOptions = {};
          if (Platform.OS === "android") {
            if(updateResponse.other.updatePriority >= HIGH_PRIORITY_UPDATE){
              updateOptions = {
                updateType: IAUUpdateKind.IMMEDIATE,
              };
              this.#inAppUpdates.addIntentSelectionListener(this.onCancelForceUpdate);
            }
          }
          this.#inAppUpdates.addStatusUpdateListener(this.installUpdateListener);
          this.#inAppUpdates.startUpdate(updateOptions);
        }
      });
  };
  
  // if the user closes update popup it will show it again.
  onCancelForceUpdate = (result) => {
    console.log('the result is for onCancelForceUpdate ---> ', result);
    if(result === '6'){
      this.checkForUpdate();
    }
  }

  installUpdateListener = (event) => {
    const {status} = event;
   // according to library documentation it should return 4 when installation is done. but it never returns 4.
    if(status === 4){
      console.log('installed update ...');
      RNRestart.Restart();
    }
  }
  
  componentDidMount() {
    console.log('calling check for update');
    this.checkForUpdate()
  }

  render() {
    return (
      <view>
        <text>
          something
        </text>
      </view>
    );
  }  
}
```

**Comment by SudoPlz** [comment]
@wahidshadab It sounds to me that the app is crashing, are you using anything to get those logs? There should be some indication of the crash.
