### ISSUE TITLE
Error: UPDATE_STATUS export type

### ISSUE THREAD

**Issue by Azshar** [SudoPlz/sp-react-native-in-app-updates#8]
<img width="338" alt="Снимок экрана 2020-10-22 в 12 10 00" src="https://user-images.githubusercontent.com/20275419/96850518-95a50280-145f-11eb-82d8-2b80a294a43d.png">

**Comment by SudoPlz** [comment]
Is your project a react native project?
Does it support typescript?

Btw you're using the alpha version of our library, you can rollback to the non alpha version of you need to.
