### ISSUE TITLE
Switch the Upgrade/Cancel button for iOS?

### ISSUE THREAD

**Issue by tonybao1** [SudoPlz/sp-react-native-in-app-updates#83]
Is it possible to switch the Upgrade and Cancel button for the iOS alert?

**Comment by SudoPlz** [comment]
Our project uses react-native-siren for iOS.
You can change the text for sure (using those options: https://github.com/GantMan/react-native-siren#options) but to change more, you'll have to take a look at the react-native-siren code.

**Comment by imki123** [comment]
https://github.com/GantMan/react-native-siren/pull/23
I have submitted a **PR to react-native-siren** to change the button position on iOS.

**Comment by imki123** [comment]
https://github.com/SudoPlz/sp-react-native-in-app-updates/pull/195 Merged
