### ISSUE TITLE
Remove dependency on jcenter

### ISSUE THREAD

**Issue by glrahulborah** [SudoPlz/sp-react-native-in-app-updates#96]
Gradle 7.0 will deprecate the use of `jcenter()` to resolve dependencies. You will still be able to use JCenter as a repository, but Gradle will emit a deprecation warning. The `jcenter()` method will be removed in the next major release.

Source: https://blog.gradle.org/jcenter-shutdown

Please migrate or use `mavenCentral()` as an alternative to resolve dependencies.

**Comment by mwerder** [comment]
@SudoPlz I think there is already a [PR](https://github.com/SudoPlz/sp-react-native-in-app-updates/pull/65).

**Comment by SudoPlz** [comment]
Merged and released on 1.2.0
